In [1]:
import pandas as pd
import numpy as np

In [31]:
from pandas import Series, DataFrame

Series

In [32]:
#일련의 객체를 담을 수 있는 1차원 배열 같은 자료구조
#색인(index)이라고 하는 배열의 데이터와 연관된 이름을 가지고있다.
#가장 간단한 Series객체는 배열 데이터로부터 생성 가능.

In [33]:
obj = pd.Series([4, 7, -5, 3])

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
#왼: 색인 오:색인값
#위는 데이터의 색인을 지정하지 않았으니 기본 색인인 정수 0에서 N - 1(N은 데이터의 
#길이) 까지의 숫자가 표시

In [36]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [37]:
obj.index

RangeIndex(start=0, stop=4, step=1)

각 데이터를 지칭하는 색인을 지정하여 Series 객체를 생성해야 할 때

In [38]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [39]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [40]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [41]:
#Numpy 배열과 비교, 단일 값을 선택 or 여러 값을 선택할 때 색인으로 라벨 사용 가능.

In [42]:
obj2['a']

-5

In [14]:
obj2['d'] = 6

In [15]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [16]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [17]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
dtype: int64

In [24]:
#파이썬 사전형에 데이터를 저장해야 한다면 파이썬 객체로부터 Series객체를 생성할
#수도 있다.

In [25]:
#사전 객체만 가지고 Series 객체를 생성하면 생성된Seires 객체의 색인에는
#사전의 키값이 순서대로 들어간다. 색인을 정하고 싶으면 원하는 순서대로 직접 넘겨줄슁ㅆ따.

In [26]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [27]:
obj4 = pd.Series(sdata, index=states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

예제를 보면 sdata에 있는 값 중 3개만 확인할 수 있는데, California에 대한 값을 찾을
수 없기 때문. 이 값은 NaN(not a number)으로 표시되고 pandas에는 누락된 값, 혹은
NA 값으로 취급된다.
나는 앞으로 누락된 또는 NA를 누락된 데이터를 지칭하는 데 사용함.
pandas의 isnul과 noutnull함수는 누락된 데이터를 찾을 때 사용

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
#이 메서드는 Series의 인스턴스 메서드로도 존재

In [32]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Series의 유용한 기능은 산술 연산에서 색인과 라벨로 자동 정렬하는 것

In [33]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
dtype: int64

In [34]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
dtype: float64

Series 객체와 Series의 색인은 모두 name 속성이 있는데 이 속성은 pandas의 핵심 기능과
밀접한 관련이 있다.

In [36]:
obj4.name = 'population'

In [37]:
obj4.index.name = 'state'

In [38]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [39]:
#Series의 색인은 대입하여 변경할 수 있다.

In [40]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [41]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [42]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

DataFrame

DataFrame은 표 같은 스프레드시트 형식의 자료구조이고 여러 개의 컬럼이 있는데 각 컬럼
은 서로 다른 종류의 값(숫자, 문자열 등)담을 수 있다.
DataFrame은 로우와 컬럼에 대한 색인을 가지고 있는데, 색인의 모양이 같은 Series 객체를 담고 있는 파이썬 사전으로 생각하면 됨. 내부적으로 데이터는 리스트나 사전 또는 1차원 배열을 담고있는 다른 컬렉션이 아니라 하나 이상의 2차원 배열에 저장됨

DataFrame 객체는 다양한 방법으로 생성할 수 있지만 가장 흔하게 사용되는 방법은 같은
길이의 리스트에 담긴 사전을 이용하거나 Numpy 배열을 이용하는 것.

In [43]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevad', 'Nevad', 'Nevad'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [44]:
frame

state  year  pop
0   Ohio  2000  1.5
1   Ohio  2001  1.7
2   Ohio  2002  3.6
3  Nevad  2001  2.4
4  Nevad  2002  2.9
5  Nevad  2003  3.2

In [45]:
frame.head()

state  year  pop
0   Ohio  2000  1.5
1   Ohio  2001  1.7
2   Ohio  2002  3.6
3  Nevad  2001  2.4
4  Nevad  2002  2.9

In [46]:
#head메서드를 이용해서 처음 5개의 로우만 출력

In [47]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year  state  pop
0  2000   Ohio  1.5
1  2001   Ohio  1.7
2  2002   Ohio  3.6
3  2001  Nevad  2.4
4  2002  Nevad  2.9
5  2003  Nevad  3.2

In [48]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [49]:
frame2

year  state  pop debt
one    2000   Ohio  1.5  NaN
two    2001   Ohio  1.7  NaN
three  2002   Ohio  3.6  NaN
four   2001  Nevad  2.4  NaN
five   2002  Nevad  2.9  NaN
six    2003  Nevad  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
frame2['state']

one       Ohio
two       Ohio
three     Ohio
four     Nevad
five     Nevad
six      Nevad
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [53]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5

In [55]:
frame2

year  state  pop  debt
one    2000   Ohio  1.5  16.5
two    2001   Ohio  1.7  16.5
three  2002   Ohio  3.6  16.5
four   2001  Nevad  2.4  16.5
five   2002  Nevad  2.9  16.5
six    2003  Nevad  3.2  16.5

In [56]:
frame2['debt'] = np.arange(6.)

In [57]:
frame2

year  state  pop  debt
one    2000   Ohio  1.5   0.0
two    2001   Ohio  1.7   1.0
three  2002   Ohio  3.6   2.0
four   2001  Nevad  2.4   3.0
five   2002  Nevad  2.9   4.0
six    2003  Nevad  3.2   5.0

In [58]:
#리스트나 배열을 컬럼에 대입할 때는 대입하려는 값의 길이가 DataFrame의 크기와 동일
#Series를 대입하면 DataFrame의 색인에 따라 값이 대입되며 존재하지 않는 색인에는 결
#측치가 대입된다.

In [59]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [60]:
frame2['debt'] = val

In [61]:
frame2

year  state  pop  debt
one    2000   Ohio  1.5   NaN
two    2001   Ohio  1.7  -1.2
three  2002   Ohio  3.6   NaN
four   2001  Nevad  2.4  -1.5
five   2002  Nevad  2.9  -1.7
six    2003  Nevad  3.2   NaN

In [62]:
#존재하지 않는 컬럼을 대입하면 새로운 컬럼을 생성. 파이썬 사전형에서처럼 del 예약어
#를 사용해서 컬럼을 삭제
#del 예약어에 대한 예제, state컬럼 값이 'Ohio'인지 아닌지에 대한 불리언값을 담고 있
#는 새로운 컬럼

In [63]:
frame2['eastern'] = frame2.state == 'Ohio'

In [64]:
frame2

year  state  pop  debt  eastern
one    2000   Ohio  1.5   NaN     True
two    2001   Ohio  1.7  -1.2     True
three  2002   Ohio  3.6   NaN     True
four   2001  Nevad  2.4  -1.5    False
five   2002  Nevad  2.9  -1.7    False
six    2003  Nevad  3.2   NaN    False

In [65]:
#del 예약어를 이용하여 컬럼을 삭제

In [66]:
del frame2['eastern']

In [67]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [68]:
#중첩된 사전을 이용해서 데이터를 생성할 수 있다.
#다음과 같은 중첩된 사전이 있다고 하자.

In [69]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [70]:
#이 중첩된 사전을 DataFrame에 넘기면 바깥에 있는 사전의 키는 컬럼이 되고 안에 있는 

In [71]:
#키는 로우가 된다.

In [72]:
frame3 = pd.DataFrame(pop)

In [73]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [74]:
#Numpy 배열과 유사한 문법으로 데이터를 전치할 수 있다.

In [75]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [76]:
#중첩된 사전을 이용해서 DataFrame을 생성할 때 안쪽에 있는 사전값은 키값별로 조합되어

In [77]:
#결과의 색인이 되지만 색인을 직접 지정하면 지정된 색인으로 DataFrame을 생성

In [78]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [79]:
#Series 객체를 담고 있는 사전 데이터도 같은 방식으로 취급한다.

In [80]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [81]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [82]:
#index와 columns에 name 속성을 지정했다면 이 역시 함께 줄력

In [83]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [84]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [85]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [86]:
#DataFrame의 컬럼이 서로 다른 dtype을 가지고 있다면 모든 컬럼을 수용하기 위해
#그 컬럼의 배열의 dtype이 선택된다.

In [87]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevad', 2.4, -1.5],
       [2002, 'Nevad', 2.9, -1.7],
       [2003, 'Nevad', 3.2, nan]], dtype=object)

5.1.3 색인 객체
pandas의 색인 객체는 표 형식의 데이터에서 각 로우와 컬럼에 대한 이름과 다른 메타데이터(축의 이름 등)를 저장하는 객체다. Series나 DataFrame 객체를 생성할 때 사용되는 배열이나 다른 순차적인 이름은 내부적으로 색인으로 변환된다.

In [88]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [89]:
index = obj.index

In [90]:
index

Index(['a', 'b', 'c'], dtype='object')

In [91]:
index[1:]

Index(['b', 'c'], dtype='object')

In [92]:
#색인 객체는 변경이 불가능하다.

In [93]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [94]:
labels = pd.Index(np.arange(3))

In [95]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [96]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [97]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [98]:
obj2.index is labels

True

In [99]:
#배열과 유사하게 Index 객체도 고정 크기로 동작한다.

In [100]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [101]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [102]:
'Ohio' in frame3.columns

True

In [103]:
2003 in frame3.index

False

In [104]:
#파이썬의 집합과 달리 pandas의 인덱스는 중복되는 값을 허용

In [105]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [106]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

5.2 핵심 기능 Series나 DataFrame에 저장된 데이터를 다루는 기본적인 방법을 설명

5.2.1 재색인
pandas 객체의 중요한 기능 중 하나는 reindex인데, 새로운 색인에 맞도록 객체를 새로 생성한다. 아래 간단한 예제를 살펴보자.

In [107]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [108]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [109]:
#이 Series 객체에 대해 reindex를 호출하면 데이터를 새로운 색인에 맞게 재배열하고,
#존재하지 않는 색인값이 있다면 NaN을 추가한다.

In [110]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [111]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

시계열 같은 순차적인 데이터를 재색인할 때 값을 보간하거나 채워 넣어야 할 경우가 있다. method 옵션을 이용해서 이를 해결할 수 있으며, ffill 같은 메서드를 이용해서 누락된 값을 직전의 값으로 채워 넣을 수 있다.

In [112]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [113]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [114]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [115]:
#DataFrame에 대한 reindex는 로우(색인), 컬럼 또는 둘 다 변경 가능하다. 그냥 순서만
#전달하면 로우가 재색인된다.

In [116]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [117]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [118]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [119]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [120]:
#컬럼은 columns 예약어를 사용해서 재색인할 수 있다.

In [121]:
states = ['Texas', 'Utah', 'California']

In [122]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [123]:
#재색인은 loc를 이용해서 라벨로 색인하면 좀 더 간결하게 할 수 있으며 대부분의
#사용자는 명시적으로 이 방식을 사용하는것을 선호

In [126]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

5.2.2 하나의 로우나 컬럼 삭제하기
색인 배열, 또는 삭제하려는 로우나 컬럼이 제외된 리스트를 이미 가지고 있다면 로우나 컬럼을 쉽게 삭제할 수 있는데 이 방법은 데이터의 모양을 변경하는 작업이 필요하다.
drop메서드를 사용하면 선택한 값들이 삭제된 새로운 객체를 얻을 수 있다.

In [127]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [128]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [129]:
new_obj = obj.drop('c')

In [130]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [131]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [132]:
#DataFrame에서는 로우와 컬럼 모두에게서 값을 삭제할 수 있다.

In [133]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [134]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
#drop 함수에 인자로 로우 이름을 넘기면 해당 로우(axis 0)의 값을 모두 삭제

In [136]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
#컬럼의 값을 삭제할 때는 axis=1 또는 axis='columns'를 인자로 넘겨주면 된다.

In [138]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [139]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [140]:
#drop 함수처럼 Series나 DataFrame의 크기 또는 형태를 변경하는 함수는 새로운 객체를
#반환하는 대신 원본 객체를 변경한다.

In [141]:
obj.drop('c', inplace=True)

In [142]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [143]:
#inplace 옵션을 사용하는 경우 버려지는 값을 모두 삭제하므로 주의해서 사용하자.

5.2.3 색인하기, 선택하기, 거르기
Series의 색인(obj[...])은 Numpy 배열의 색인과 유사하게 동작하지만 정수가 아니어도 된다는 점이 다르다. 몇 가지 예제를 살펴보자.

In [144]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [145]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [146]:
obj['b']

1.0

In [147]:
obj[1]

1.0

In [148]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [149]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [150]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [151]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [152]:
#라벨 이름으로 슬라이싱하면 시작점과 끝점을 포함한다는 것이 일반 파이썬에서의 슬라이

In [153]:
#싱과 다른점이다.

In [154]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [155]:
#슬라이싱 문법으로 선택된 영역에 값을 대입하는 것은 생각하는 대로 동작한다.

In [156]:
obj['b':'c'] = 5

In [157]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [158]:
#색인으로 DataFrame에서 하나 이상의 컬럼 값을 가져올 수 있다.

In [159]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [160]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [162]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [173]:
#슬라이싱으로 로우를 선택하거나 불리언 배열로 로우를 선택할 수 있다.

In [174]:
data[:2]

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7

In [175]:
data[2:]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [176]:
data[data['three'] > 5]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [177]:
#data[:2] 형식의 문법으로 로우를 선택할 수 있음. []연산자에 단일 값을 넘기거나
#리스트를 넘겨서 여러 컬럼을 선택할 수 있음
#다른 방법으로는 스칼라 비교를 이용해 생성된 불리언 DataFrame을 사용해서 값을 선택

In [178]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [179]:
data[data < 5] = 0

In [180]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

loc과 iloc으로 선택하기

DataFrame의 로우에 대해 라벨로 색인하는 방법으로 특수한 색인 필드인 loc과 iloc을 소개한다. 이 방법을 이용하면 Numpy와 비슷한 방식에 추가적으로 축의 라벨을 사용하여 DataFrame의 로우와 컬럼을 선택할 수 있다. 축 이름을 선택할 때는 loc을, 정수 색인으로 선택할 때는 iloc을 사용.

In [181]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [182]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [183]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [184]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [185]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [186]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

5.2.4 정수 색인

정수 색인으로 pandas 객체를 다루다보면 리스트나 튜플 같은 파이썬 내장 자료구조에서 색인을 다루는 방법과의 차이점 때문에 실수하게 되는 경우가 있다. 예를 들어 다음 코드가 에러를 발생할 것이라고 생각하지 않을 것이다.

In [249]:
ser = pd.Series(np.arange(3.))
ser
ser[-1]

KeyError: -1

In [188]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

ser
ser[-1]
이 경우 pandas는 라벨 색인을 찾는 데 실패하므로 정수 색인으로 값을 찾는다. 하지만 이를 어떤 경우에도 버그 없이 잘 작동하도록 구현하기란 쉽지 않다. 라벨 색인이 0, 1, 2를 포함하는 경우 사용자가 라벨 색인으로 선택하려는 것인지 정수 색인으로 선택하려는 것인지 추축하기 쉽지 않다.

In [189]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [190]:
#반면 정수 기반의 색인을 사용하지 않는 경우 이런 모호함은 사라진다.

In [191]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [192]:
ser2[-1]

2.0

In [193]:
ser[:1]

0    0.0
dtype: float64

In [194]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [195]:
ser.iloc[:1]

0    0.0
dtype: float64

5.2.5 산술 연산과 데이터 정렬

pandas에서 가장 중요한 기능 중 하나는 다른 색인을 가지고 있는 객체 간의 산술 연산이다. 객체를 더할 때 짝이 맞지 않는 색인이 있다면 결과에 두 색인이 통합된다. 데이터베이스를 사용해본 경험이 있다면 색인 라벨에 대한 외부 조인과 유사하게 동작한다고 생각할 수 있다.

In [196]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [197]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=['a', 'c', 'e', 'f', 'g'])

In [198]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [199]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [200]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [201]:
#서로 겹치는 색인이 없는 경우 데이터는 NA 값이 된다. 산술 연산 시 누락된 값은 전파
#된다. DataFrame의 경우 정렬은 로우와 컬럼 모두에 적용된다.

In [202]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Oregon'])

In [203]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [204]:
df1

b    c    d
Ohio    0.0  1.0  2.0
Texas   3.0  4.0  5.0
Oregon  6.0  7.0  8.0

In [205]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [206]:
df1 + df2

b   c     d   e
Ohio     3.0 NaN   6.0 NaN
Oregon  15.0 NaN  18.0 NaN
Texas    9.0 NaN  12.0 NaN
Utah     NaN NaN   NaN NaN

'c' 와 'e' 컬럼이 양쪽 DataFrame 객체에 존재하지 않으므로 결과에서는 모두 없는 값으로 나타난다. 로우 역시 마찬가지로 양쪽에 다 존재하지 않는 라벨에 대해서는 없는 값으로 나타난다. 공통되는ㄴ 컬럼 라벨이나 로우 라벨이 없는 DataFrame을 더하면 결과에 아무것도 나타나지 않을 것이다.

In [207]:
df1 = pd.DataFrame({'A': [1, 2]})

In [208]:
df2 = pd.DataFrame({'B': [3, 4]})

In [209]:
df1

A
0  1
1  2

In [210]:
df2

B
0  3
1  4

In [211]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

산술 연산 메서드에 채워 넣을 값 지정하기

서로 다른 색인을 가지는 객체 간의 산술 연산에서 존재하지 않는 축의 값을 특수한 값(0같은)으로 지정하고 싶을 때는 다음과 같이 할 수 있다.

In [212]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))

In [213]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [214]:
df2.loc[1, 'b'] = np.nan

In [215]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [216]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [217]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [218]:
#df1에 add메서드를 사용하고, df2와 fill_value 값을 인자로 전달함.

In [219]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [220]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [221]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [222]:
#Series나 DataFrame을 재색인할 때도 fill_value를 지정할 수 있다.

In [223]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

DataFrame과 Series 간의 연산

다른 차원의 Numpy 배열과의 연산처럼 DataFrame과 Series 간의 연산도 잘 정의되어 있다.

먼저 2차원 배열과 그 배열의 한 로우의 차이에 대해 생각할 수 있는 예제를 살펴보자.

In [224]:
arr = np.arange(12.).reshape((3, 4))

In [225]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [226]:
arr[0]

array([0., 1., 2., 3.])

In [227]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

arr에서 arr[0]을 빼면 계산은 각 로우에 대해 한 번씩만 수행된다. 이를 브로드캐스팅이라고 하는데 더 자세한 내용은 부록A   
DataFrame과 Series간의 연산은 이와 유사

In [228]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [229]:
series = frame.iloc[0]

In [230]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [231]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [232]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [233]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [234]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [235]:
#각 로우에 대해 연산을 수행하고 싶다면 산술 연산 메서드를 사용하면 된다.

In [236]:
series3 = frame['d']

In [237]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [238]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [239]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [240]:
#인자로 넘기는 axis값은 연산을 적용할 축 번호다.axis='index'나 axis=0은 DataFrame의
#로우를 따라 연산을 수행하라는 의미이다.

5.2.6 함수 적용과 매핑  
pandas 객체에도 Numpy의 유니버설 함수(배열의 각 원소에 적용되는 메서드)를 적용할 수 있다.

In [241]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [242]:
frame

b         d         e
Utah    0.241162  0.280225 -0.280272
Ohio   -0.190851  0.455565 -2.677783
Texas   0.882902  1.874271  0.400700
Oregon -2.053760 -0.641054 -1.201365

In [243]:
np.abs(frame)

b         d         e
Utah    0.241162  0.280225  0.280272
Ohio    0.190851  0.455565  2.677783
Texas   0.882902  1.874271  0.400700
Oregon  2.053760  0.641054  1.201365

In [244]:
f = lambda x: x.max() - x.min()

In [245]:
frame.apply(f)

b    2.936662
d    2.515326
e    3.078483
dtype: float64

여기서 함수 f는 Series의 최댓값과 최솟값의 차이를 계산하는 함수다. frame의 각 컬럼에 대해 한 번만 수행되어 결과값은 계산을 적용한 컬럼을 색인으로 하는 Series를 반환한다.
apply 함수에 axis='columns'인자를 넘기면 각 로우에 대해 한 번씩만 수행된다.

In [246]:
frame.apply(f, axis='columns')

Utah      0.560497
Ohio      3.133348
Texas     1.473572
Oregon    1.412706
dtype: float64

배열에 대한 일반적인 통계(sum이나 mean같은)는 DataFrame의 메서드로 존재하므로 apply메서드를 사용할 필요 없다.
apply 메서드에 전달된 함수는 스칼라값을 반환할 필요가 없다. 여러 값을 가진 Series를 반환해도 된다.

In [247]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [248]:
frame.apply(f)

b         d         e
min -2.053760 -0.641054 -2.677783
max  0.882902  1.874271  0.400700

배열의 각 원소에 적용되는 파이썬의 함수를 사용할 수도 있다. frame 객체에서 실숫값을 문자열 포맷으로 변환하고 싶다면 applymap을 이용해서 다음과 같이 할 수 있다.

In [250]:
format = lambda x: '%.2f' % x

In [251]:
frame.applymap(format)

b      d      e
Utah    -1.29   1.68   0.47
Ohio    -0.94   0.08   0.12
Texas   -0.21   0.70   0.48
Oregon   0.80  -0.48  -1.26

In [252]:
#메서드의 이름이 applymap인 이유는 Series는 각 원소에 적용할 함수를 지정하기 위한 map
#메서드를 가지고 있기 때문

In [255]:
frame['e'].map(format)

Utah       0.47
Ohio       0.12
Texas      0.48
Oregon    -1.26
Name: e, dtype: object

5.2.7 정렬과 순위  
어떤 기준에 근거해서 데이터를 정렬하는 것 역시 중요한 명령이다. 로우나 컬럼의 색인을 알파벳순으로 정렬하려면 정렬된 새로운 객체를 변환하는 sort_index메서드를 사용하면된다.

In [257]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [259]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [260]:
#DataFrame은 로우나 컬럼 중 하나의 축을 기준으로 정렬할 수 있다.

In [261]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [262]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [263]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [265]:
frame.sort_index(axis=1, ascending=True)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [266]:
obj = pd.Series([4, 7, -3, 2])

In [267]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [268]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [269]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [270]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [271]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [272]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [280]:
#여러 개의 컬럼을 정렬
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

순위는 정렬과 거의 흡사한데, 1부터 배열의 유효한 데이터 개수까지 순서를 매긴다. 기본적으로 Series와 DataFrame의 rank 메서드는 동점인 항목에 대해서는 평균 순위를 매긴다.

In [283]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [284]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [285]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [288]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [289]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                     'c': [-2, 5, 8, -2.5]})

In [300]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [301]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

5.2.8 중복 색인  
지금까지 살펴본 모든 예제는 축 이름(색인값)이 유일한 경우밖에 없었다. pandas의 많은 함수 (reindex 같은)에서 색인값은 유일해야 하지만 의무적이지는 않다. 중복된 색인값을 가지는 Series 객체를 살펴보자.

In [302]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [303]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [304]:
obj.index.is_unique

False

중복되는 색인값이 있다면 색인을 이용해서 데이터에 접근했을 때 다르게 동작한다. 중복되는 색인값이 없을 때는 색인을 이용해서 데이터에 접근하면 스칼라값을 반환하지만 중복된느 색인값이 있을 때는 하나의 Series 객체를 반환한다.

In [305]:
obj['a']

a    0
a    1
dtype: int64

In [306]:
obj['c']

4

이는 라벨이 반복되는지 여부에 따라 색인을 이용해서 선택한 결과가 다를 수 있기 때문에 코드를 좀 더 복잡하게 만들 수 있다. 
DataFrame에서 로우를 선택하는 것도 동일하다.

In [308]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [309]:
df

0         1         2
a  1.055658 -0.565307  2.287971
a -1.441540  1.210626  1.076951
b  0.147383 -0.623716  1.470966
b -0.417710 -0.146346 -0.496746

In [310]:
df.loc['b']

0         1         2
b  0.147383 -0.623716  1.470966
b -0.417710 -0.146346 -0.496746

5.3 기술 통계 계산과 요약    
pandas 객체는 일반적인 수학 메서드와 통계 메서드를 가지고 있다. 이 메서드의 대부분은 하나의 Series나 DataFrame의 로우나 컬럼에서 단일 값 (합이나 평균 같은)을 구하는 축소(reductions) 혹은 요약 통계(summary statistics)범주에 속한다. 순수 Numpy 배열에서 제공하는 동일한 메서드와 비교하여 pandas의 메서드는 처음부터 누락된 데이터를 제외하도록 설계되었다. 다음과 같은 DataFrame을 생각해보자.

In [311]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'],
                 columns=['one', 'two'])

In [312]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [313]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [314]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [317]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [318]:
df.idxmax()

one    b
two    d
dtype: object

In [319]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [320]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [321]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [322]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

5.3.1 상관관계와 공분산   
상관관계나 공분산 같은 요약 통계 계산은 두 쌍의 인자를 필요로 한다. pandas-datareader패키지를 이용해서 야후! 금융 사이트에서 구한 주식가격과 시가총액을 담고있는 다음 DataFrame을 생각해보자. 

In [324]:
conda install pandas-datareader

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\user\anaconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.7.22  |                0         125 KB
    pandas-datareader-0.9.0    |             py_0          72 KB
    ------------------------------------------------------------
                                           Total:         196 KB

The following NEW packages will be INSTALLED:

  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.9.0-py_0

The following packages will be UPDATED:

  ca-certificates                               2020.6.24-0 --> 2020.7.22-0




ca-certificates-2020 | 125 KB    |            |   0% 
ca-certificates-2020 | 125 KB    | #2         |  13% 
ca-certificates-2020 | 125 KB    | ########## | 100% 

pandas-datareader-0. | 72 KB     |

In [325]:
#pandas_datareader 모듈을 이용해서 주가 정보를 다운로드하자.

In [326]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [327]:
returns = price.pct_change()

In [328]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-08-26  0.013599 -0.003771  0.021620  0.027459
2020-08-27 -0.011954  0.003866  0.024554 -0.010924
2020-08-28 -0.001620  0.003369  0.010283  0.006168
2020-08-31  0.033912 -0.014072 -0.014766 -0.006221
2020-09-01  0.039833  0.000730  0.007715  0.016234

In [329]:
returns['MSFT'].corr(returns['IBM'])

0.5796277774337827

In [330]:
returns['MSFT'].cov(returns['IBM'])

0.0001603356235848256

In [333]:
returns.MSFT.corr(returns.IBM)

0.5796277774337827

In [ ]:
#반면에 DataFrame에서 corr과 cov 메서드는 DataFrame 행렬에서 상관관계와 공분산을
#계산한다.

In [334]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.505112  0.697239  0.654423
IBM   0.505112  1.000000  0.579628  0.533570
MSFT  0.697239  0.579628  1.000000  0.780522
GOOG  0.654423  0.533570  0.780522  1.000000

In [335]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000336  0.000148  0.000221  0.000196
IBM   0.000148  0.000256  0.000160  0.000140
MSFT  0.000221  0.000160  0.000299  0.000221
GOOG  0.000196  0.000140  0.000221  0.000268

In [337]:
returns.corrwith(returns.IBM)

AAPL    0.505112
IBM     1.000000
MSFT    0.579628
GOOG    0.533570
dtype: float64

In [338]:
#DataFrame을 넘기면 맞아떨어지는 컬럼 이름에 대한 상관관계를 계산한다.
#여기서 나는 시가총액의 퍼센트 변화율에 대한 상관관계를 계산해보았다.

In [339]:
returns.corrwith(volume)

AAPL   -0.081490
IBM    -0.099531
MSFT   -0.046920
GOOG   -0.147364
dtype: float64

In [340]:
#axis='columns' 옵션을 넘기면 각 컬럼에 대한 상관관계와 공분산을 계산한다.
#모든 경우 데이터는 상관관계를 계산하기 전에 색인의 이름순으로 정렬된다.

5.3.2 유일값, 값 세기, 멤버십  
또 다른 종류의 메서드로는 1차원 Series에 담긴 값의 정보를 추출하는 메서드가 있다.

In [341]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [342]:
uniques = obj.unique()

In [344]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

유일값은 정렬된 순서대로 반환되지 않지만 필요하다면 uniques.sort()를 이용해서 
나중에 정렬할 수 있다. value_counts 메서드는 Series에서 도수(frequency)를 계산
해서 반환.

In [347]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

value_counts에서 반환하는 Series는 담고 있는 값을 내림차순으로 정렬한다. value_counts 메서드는 pandas의 최상위 메서드로, 어떤 배열이나 순차 자료구조에서도 사용가능

In [348]:
pd.value_counts(obj.values, sort=False)

b    2
d    1
c    3
a    3
dtype: int64

isin 메서드는 어떤 값이 Series에 존재하는지 나타내는 불리언 벡터를 반환하는데, Series나 DataFrame의 컬럼에서 값을 골라내고 싶을 때 유용하게 사용할 수 있다.

In [349]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [350]:
mask = obj.isin(['b', 'c'])

In [351]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [352]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [353]:
#isin과 관련이 있는Index.get_indexer 메서드는 여러 값이 들어 있는 배열에서
#유일한 값의 색인 배열을 구할 수 있다.

In [354]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [355]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [356]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [357]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [358]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [359]:
result = data.apply(pd.value_counts).fillna(0)

In [361]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

5.4 마치며  
다음 장에서는 pandas를 이용해서 데이터셋을 읽고(또는 로딩) 쓰는 도구를 다룸
그 다음 데이터를 정제하고 분석하고 시각화하는 도구를 더 깊이 살펴봄